/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Dock extends javax.swing.JDialog {

    int Resolucion_Pantalla=(Toolkit.getDefaultToolkit().getScreenSize().width/2)-289;
        int   xMouse;
        int   yMouse;
    /**
     * Creates new form Dock
     */
    public Dock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(Resolucion_Pantalla,20);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Trelloname2 = new javax.swing.JLabel();
        Trello = new javax.swing.JLabel();
        Trelloname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Trelloname1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Trelloname2.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Trelloname2.setForeground(new java.awt.Color(255, 255, 255));
        Trelloname2.setText("ColorHut");
        getContentPane().add(Trelloname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, 30));

        Trello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trello_off.png"))); // NOI18N
        Trello.setText("jLabel1");
        Trello.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrelloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TrelloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TrelloMouseReleased(evt);
            }
        });
        getContentPane().add(Trello, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        Trelloname.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Trelloname.setForeground(new java.awt.Color(255, 255, 255));
        Trelloname.setText("Trello");
        getContentPane().add(Trelloname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Colorhut_off.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        Trelloname1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Trelloname1.setForeground(new java.awt.Color(255, 255, 255));
        Trelloname1.setText("Trello");
        getContentPane().add(Trelloname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fondoMouseDragged(evt);
            }
        });
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMousePressed(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 72));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrelloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrelloMousePressed
ImageIcon Tr =new ImageIcon(getClass().getResource("/Imagenes/trello_on.png"));    
Trello.setIcon(Tr);
    }//GEN-LAST:event_TrelloMousePressed

    private void TrelloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrelloMouseReleased
       ImageIcon Tr =new ImageIcon(getClass().getResource("/Imagenes/trello_off.png"));    
Trello.setIcon(Tr);
    }//GEN-LAST:event_TrelloMouseReleased

    private void fondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseDragged
      int x=evt.getXOnScreen();
            int y=evt.getYOnScreen();
this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_fondoMouseDragged

    private void fondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMousePressed
      xMouse=evt.getX();
        yMouse=evt.getY();

    }//GEN-LAST:event_fondoMousePressed

    private void TrelloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrelloMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("https://trello.com"));
        } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_TrelloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dock dialog = new Dock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Trello;
    private javax.swing.JLabel Trelloname;
    private javax.swing.JLabel Trelloname1;
    private javax.swing.JLabel Trelloname2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
